name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master # or main, based on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Ensure you're using a compatible version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Inject environment variables and build the React app
      - name: Build React app with environment variables
        run: |
          echo "PUBLISH_API_VERSION=${{ secrets.PUBLISH_API_VERSION }}" >> .env
          echo "QUERY_API_VERSION=${{ secrets.QUERY_API_VERSION }}" >> .env
          npm run build
        env:
          PUBLISH_API_VERSION: ${{ secrets.PUBLISH_API_VERSION }}
          QUERY_API_VERSION: ${{ secrets.QUERY_API_VERSION }}

      # Step 5: Create .nojekyll file to disable Jekyll processing on GitHub Pages
      - name: Create .nojekyll
        run: echo "" > ./build/.nojekyll

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # React build output directory
