name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master # Trigger deployment on pushes to the master branch
  workflow_dispatch: # Allow manual runs with custom inputs
    inputs:
      publish_api_version:
        description: "PUBLISH_API_VERSION to use"
        required: true
        default: "1"
      query_api_version:
        description: "QUERY_API_VERSION to use"
        required: true
        default: "1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Inject environment variables and build the React app
      - name: Build React app with environment variables
        run: |
          npm run build
        env:
          PUBLISH_API_VERSION: ${{ vars.PUBLISH_API_VERSION }}
          QUERY_API_VERSION: ${{ vars.QUERY_API_VERSION }}

      # Step 5: Deploy to GitHub Pages
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# name: Deploy React App to GitHub Pages

# on:
#   push:
#     branches:
#       - master  # Trigger deployment on pushes to the master branch

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout the code from the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Step 2: Set up Node.js
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18"

#       # Step 3: Install dependencies
#       - name: Install dependencies
#         run: npm install

#       # Step 4: Inject environment variables and build the React app
#       - name: Build React app with environment variables
#         run: |
#           echo "PUBLISH_API_VERSION=${{ secrets.PUBLISH_API_VERSION }}" >> .env
#           echo "QUERY_API_VERSION=${{ secrets.QUERY_API_VERSION }}" >> .env
#           npm run build
#         env:
#           PUBLISH_API_VERSION: ${{ secrets.PUBLISH_API_VERSION }}
#           QUERY_API_VERSION: ${{ secrets.QUERY_API_VERSION }}

#       # Step 5: Deploy to GitHub Pages
#       - name: Deploy with gh-pages
#         run: |
#           git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
#           npm run deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
