name: Build and Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensure you are using a compatible version

      # Step 3: Install root dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build React app and move it to docs folder
      - name: Build React app
        run: |
          NODE_ENV=production npm run build
          mv build docs

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
